import type { Metadata } from "next";
import "./globals.css";
import { inter } from '@/app/ui/fonts';
import Nav from "./ui/components/Nav";


export const metadata: Metadata = {
  title: "Qinghao Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <Nav />
        {/* Main content area */}
        {children}
      </body>
    </html>
  );
}
